---
- hosts: all
  gather_facts: no
  sudo: yes
  tasks:
  - name: change yaml file for proxy
    shell: |
      sudo touch test.txt
      sudo echo "proxy:" >> test.txt
      sudo echo "    https: http://10.36.1.132:3128" >> test.txt
      
